### ISSUE TITLE
[Promotion / Discussion] Dockerfile for cottontaildb

### ISSUE THREAD

**Issue by sauterl** [ppanopticon/cottontaildb#11]
Since cottontaildb is very much de facto under the [vitrivr](https://github.com/vitrivr) umbrella, I pushed a (work in progress) [Dockerfile](https://github.com/vitrivr/vitrivr-docker/blob/vitrivr2019/cottontaildb/Dockerfile) to [vitrivr-docker](https://github.com/vitrivr/vitrivr-docker)

Any feedback is welcome (hence this thread)

**Comment by lucaro** [comment]
Since docker containers are designed to be immutable, storing dynamic data inside them is not recommended. Such data should be stored outside of the container itself, preferably (from dockers point of view) inside a volume (see https://docs.docker.com/storage/volumes/). Postgres for example briefly explains how to do this with their official image: https://hub.docker.com/_/postgres?tab=description#where-to-store-data

A cottontaildb container should be set up in a similar way.

**Comment by ppanopticon** [comment]
This has been resolved!

From now on, if you create a version tag (e.g. v1.0) on the master branch, GitHub will automatically generate and publish a docker image for Cottontail DB. For now, it will be published as Package in the repo. However, we can also publish it to the vitrivr DockerHub in the near future.
